import { Inter } from 'next/font/google'
import './ui/globals.css'
import { AuthProvider } from './Provider'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Nextjs Admin ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
   
   <AuthProvider>
        {children}
        </AuthProvider>
        </body>
     
    </html>
  )
}
